name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  tests:
    needs: generate
    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
 
    - name: Installing ollama
      uses: pydantic/ollama-action@v3
      with:
        model: llama3.2:latest

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
          stack-arguments: --stack-yaml ${{ matrix.stack-yaml }}
  
  docs:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json

    - name: Build docs
      working-directory: docs
      run: |
        npm ci
        npm run build
